global:
  slack_api_url: #API_WEBHOOK_SLACK
  smtp_smarthost: 
  smtp_from: SMTP_FROM
  smtp_require_tls: false
  http_config:
    proxy_url: #proxy


route:

 group_by: [uptime, cpu]
 receiver: 'slack-alert'
 group_interval: 30m
 group_wait: 1m
 repeat_interval: 1m

 routes:
 - match:
    severity: warning
   receiver: 'slack-alert'

 routes:
 - match:
    severity: critical
   receiver: 'slack-alert'

receivers:

- name: 'email-alert'
  email_configs:
  - to: jennifer_souza_martins@hotmail.com
    send_resolved: true

- name: 'slack-alert'
  slack_configs:
  - send_resolved: true
    username: jennieteste
    color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
    title_link: #linkdodash
    icon_emoji: ':fire:'
    channel: #nomedochannel
    title: ATENÇÃO!!!
    text: "<!channel>{{ range .Alerts }}\n*Description:* {{ .Annotations.description }}\n*Summary:* {{ .Annotations.summary }}\n{{ end }}"

templates:
- '/etc/prometheus/default.tmpl'
