global:
  slack_api_url: SLACK_API_URL
  smtp_smarthost: PROMETHEUS_SMTP
  smtp_from: SMTP_FROM
  smtp_require_tls: false

route:

 group_by: [uptime, cpu]
 receiver: 'slack-alert'
 group_interval: 30s
 group_wait: 1m
 repeat_interval: 3m

 routes:
 - match:
    severity: attention
   group_by: [cpu]
   receiver: 'slack-alert'

 routes:
 - match:
    severity: warning
   group_by: [cpu]
   receiver: 'slack-alert'

 routes:
 - match:
    severity: critical
   receiver: 'email-alert'


receivers:

- name: 'email-alert'
  email_configs:
  - to: TO
    send_resolved: true

- name: 'slack-alert'
  slack_configs:
  - send_resolved: true
    username: USERNAME
    channel: CHANNEL
    text: "<!channel> \ndescription: {{ .CommonAnnotations.description }}\nsummary: {{ .CommonAnnotations.summary }}"

templates:
- '/etc/prometheus/default.tmpl'
