version: '2'

services:

  prometheus:
   image: prom/prometheus:latest
   command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--storage.tsdb.retention=200h'
    - '--web.enable-lifecycle'
    # restart: unless-stopped
   privileged: true
   ports:
    - "9090:9090"
   volumes:
    - prometheus:/etc/prometheus/data
   hostname: prometheus
   container_name: prometheus
   restart: always
   logging:
    driver: "json-file"
    options:
     max-size: "250m"
     max-file: "3"

  alertmanager:
   image: prom/alertmanager:latest
   env_file: './environment.env'
   privileged: true
   ports:
    - "9093:9093"
   hostname: alertmanager
   container_name: alertmanager
   restart: unless-stopped
   logging:
    driver: "json-file"
    options:
     max-size: "250m"
     max-file: "3"
     
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "9100:9100"
      
  grafana:
    image: grafana/grafana:latest
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana


volumes:
 prometheus:
 grafana_data:
