version: '3'

services:

  prometheus:
   image: prometheus:latest
   command:  prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention=30d
   privileged: true
   ports:
    - "9090:9090"
   volumes:
    - prometheus:/etc/prometheus/data
   hostname: prometheus
   container_name: prometheus
   restart: always
   logging:
    driver: "json-file"
    options:
     max-size: "250m"
     max-file: "3"

  alertmanager:
   image: alertmanager:latest
   env_file: './environment.env'
   command: /etc/prometheus/run.sh
   privileged: true
   ports:
    - "9093:9093"
   hostname: alertmanager
   container_name: alertmanager
   restart: always
   logging:
    driver: "json-file"
    options:
     max-size: "250m"
     max-file: "3"


volumes:
 prometheus:
  external:
   name: prometheus
